### ISSUE TITLE
(View Posts) link for author named Shubhra is not working

### ISSUE THREAD

**Issue by srishti-nema** [leomvit/leomvit.github.io#104]
### Bug reports:
View posts link for author named "Shubhra Dixit" is not working. Add a page in _authors folder to resolve this issue. A mention of the same is done [here](https://github.com/leomvit/leomvit.github.io/pull/102#issuecomment-703862217).

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by sk6298** [comment]
I would like to give it a try.

**Comment by srishti-nema** [comment]
@sk6298  Sure, go ahead! I have assigned you this.

**Comment by prix04** [comment]
@srishti-nema i want to work on this...should i go ahead?

**Comment by prix04** [comment]
@srishti-nema I think this issue has been resoloved. is that right @srishti-nema @Shubhra-07

**Comment by srishti-nema** [comment]
Sorry for the late response @prix04 . Yes you are right. This issue has been resolved. Thanks for pointing out. Closing this.
