### ISSUE TITLE
Setup test builds

### ISSUE THREAD

**Issue by cseas** [leomvit/leomvit.github.io#107]
Currently, there's no sure way of knowing whether an incoming Pull Request works as expected or not. 

It'd be really great to setup a "test" build using something like Netlify or Vercel that builds the incoming changes on a test url so the reviewer can verify how the incoming changes exactly change the website.

This would also make the review process much faster.

[Example of Netlify deploy preview](https://github.com/JedWatson/react-select/pull/4233)

**Comment by cseas** [comment]
I've setup the test builds with Netlify. Click on "Details" in the Netllify deploy preview check in #109 

@AvikantSrivastava @srishti-nema Please check if this is alright and whether the checks make sense. I'll modify them as needed. The logs should be publicly visible so let me know if you get problems accessing the details of any check.

**Comment by srishti-nema** [comment]
@cseas This looks okay. I think you just added the standard tests right without customizing anything. I think it is okay for now.
