### ISSUE TITLE
Typographic alignment on Authors Page

### ISSUE THREAD

**Issue by AvikantSrivastava** [leomvit/leomvit.github.io#120]
## Typographic alignment on [Author Page ](https://leomvit.com/authors-list.html)
Please change the order of Authors in an alphabetical way.

**Comment by codewithkushagra** [comment]
can I work on this issue

**Comment by codewithkushagra** [comment]
can I work on this issue @AvikantSrivastava

**Comment by AvikantSrivastava** [comment]
> can I work on this issue @AvikantSrivastava

Sure go ahead and make a PR

**Comment by codewithkushagra** [comment]
Okay, I have made a PR, please review when you get time, @AvikantSrivastava @kaushikikrityy

**Comment by AvikantSrivastava** [comment]
This issue was solved int his PR https://github.com/leomvit/leomvit.github.io/pull/121
I am closing it now :D
