### ISSUE TITLE
Facebook page link broken in the contact section

### ISSUE THREAD

**Issue by perfect10-vst** [leomvit/leomvit.github.io#73]
The link that leads to the facebook page says 'This page is not available' on Facebook.

**Comment by KaushikiKrity** [comment]
I have updated this issue . Please give a look .

**Comment by perfect10-vst** [comment]
Still broken.
Better if we remove it outright?
We don't use Facebook anyway

**Comment by KaushikiKrity** [comment]
Someone have to merge it !! then it will be working. But I will try to update it again.

**Comment by KaushikiKrity** [comment]
I have updated again please merge!

**Comment by srishti-nema** [comment]
@kaushikikrityy I can see that you closed your PR. Please try to sync your repository with this one in case you are facing problems and create the PR again for it to be reviewed.

**Comment by AvikantSrivastava** [comment]
Changes have been observed,  [Pull Request](https://github.com/leomvit/leomvit.github.io/pull/81) has been merged. 
Closing this issue.
