### ISSUE TITLE
Change Whatsapp link to Discord link.

### ISSUE THREAD

**Issue by AvikantSrivastava** [leomvit/leomvit.github.io#97]
1. Change the line https://github.com/leomvit/leomvit.github.io/blob/ab07a2511116e0493a54b88e1c782a7cb57ef292/_pages/contact.html#L53 to 'Join our Discord Server'.
2. Change the WhatsApp link to the discord server link.
https://github.com/leomvit/leomvit.github.io/blob/ab07a2511116e0493a54b88e1c782a7cb57ef292/_pages/contact.html#L52
Discord link: 'https://discord.gg/VuhbU4P'

**Comment by lucasTovo** [comment]
Im made an pull request to this issue, please review it, thank you.

**Comment by KaushikiKrity** [comment]
I updated it .. please review.

**Comment by AvikantSrivastava** [comment]
Closing this issue as it was resolved in https://github.com/leomvit/leomvit.github.io/pull/99
